rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/',views.add_category,name='add_category'),
    path('category/<category_name_slug>/add_page/',views.add_page,name='add_page'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('restricted/',views.restricted,name='restricted'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index ,name='index'),
    path('rango/',include('rango.urls')),
    path ('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User



# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_image',blank=True)
    
    def __str__(self) -> str:
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page,Category,UserProfile
from django.contrib.auth.models import User
import re

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput,initial=0)
    def clean(self):
        cleaned_data=self.cleaned_data
        url = cleaned_data.get('url')
        if url and not re.search(r'^https?://'):
            url = f"http://{url}"
            cleaned_data=url
        return cleaned_data
    class Meta:
        model = Page
        exclude = ('category',)

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="Please enter the title of the page.",required=True)
    views = forms.IntegerField(widget=forms.HiddenInput,initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput,initial=0)
    slug = forms.CharField(widget=forms.HiddenInput,required=False)
    class Meta:
        model = Category
        fields = ('name',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

rango/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from rango.models import Category
from rango.models import Page,User,UserProfile

from django.http import HttpResponse,HttpRequest
from rango.forms import CategoryForm,PageForm,UserForm,UserProfileForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    visitor_cookie_handler(request) 

    context_dict = {
        'categories': category_list,
        'pages': page_list,
    }
    return render(request, 'rango/index.html', context=context_dict)



def about(request):
    visitor_cookie_handler(request)  
    visits = request.session.get('visits', 1)

    context_dict = {'visits': visits}
    return render(request, 'rango/about.html', context=context_dict)




    


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None


    return render(request, 'rango/category.html', context=context_dict)

def add_category(request:HttpRequest):
    form = CategoryForm()
    if(request.method=='POST'):
        form= CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)
        
    
    return render(request, 'rango/add_category.html', context={'form':form})

def add_page(request:HttpRequest,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category=None

    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if(request.method=='POST'):

        form= CategoryForm(request.POST)
        
        if form.is_valid():
            if category:
                page:Page=form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)
        
    context_dict = {'form':form,'category':category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request:HttpRequest):
    registered = False

    if(request.method=='POST'):

        user_form= UserForm(request.POST)
        profile_form= UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user:User =user_form.save()
            user.set_password(user.password)
            user.save()
            profile:UserProfile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile_form.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/register.html', context={'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request:HttpRequest):

    if(request.method=='POST'):

        username= request.POST.get('username')
        password= request.POST.get('password')
        user = authenticate(username= username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse('Your Rango account is disabled')
        else:
            print(f'Invalid login details {username}, {password}')
            return HttpResponse('Invalid login details supplied.')
    else:
        return render(request,'rango/login.html')


def some_view(request:HttpRequest):
    if not request.user.is_authenticated():
        return HttpResponse('You are logged in.')
    else:
        return HttpResponse('You are not logged in.')


@login_required(login_url='/rango/login/')
def restricted(request:HttpRequest):
    return HttpResponse('Since you\'re  logged in, you can see this text')

def get_serverside_cookies(request:HttpRequest,cookie,default_val=None):
    val = request.session.get(cookie)
    if not val :
        val = default_val
    return val

def visitor_cookie_handler_x( response):
    visits =int(get_serverside_cookies(request,'visits','1'))
    last_visit_cookie = get_serverside_cookies(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')
    if(datetime.now()-last_visit_time).days>0:
        visits+=1
        response.set_cookie('last_visit',datetime.now())
    else:
        response.set_cookie('last_visit',last_visit_time)
        
    response.set_cookie('visits',visits)

from datetime import datetime

from datetime import datetime

def visitor_cookie_handler(request):
    visits = request.session.get('visits', 0)
    last_visit = request.session.get('last_visit')

    if last_visit:
        try:
            last_visit_time = datetime.strptime(last_visit, '%Y-%m-%d %H:%M:%S')
        except ValueError:
            last_visit_time = datetime.now()
    else:
        last_visit_time = datetime.now()

    # Increment if a day has passed (same logic as chapter)
    if (datetime.now() - last_visit_time).days >= 1:
        visits += 1
        request.session['last_visit'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        request.session['visits'] = visits
    else:
        # Initialise if missing
        if 'visits' not in request.session:
            request.session['visits'] = 1
            request.session['last_visit'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

templates/rango/about.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <title>Rango</title>
</head>
<body>
    <h1>Rango says...</h1>
    <div>here is the about page.</div>

    <div>
        <a href="{% url 'rango:index' %}">Back to Index</a>
    </div>

    <p>This tutorial has been put together by Oseke Douye.</p>

    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <p>Visits: {{ visits }}</p>
    </div>

    <div>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>
</body>
</html>

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}
    Add a Category
{% endblock %}
{% block body_block %}
        <h1></h1>
        <div>
            <form id="category_form" method="post">
                {% csrf_token%}
                {% for hidden in form.hidden_fields %}
                    {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{field.errors}}
                    {{field.help_text}}
                    {{field}}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>
    {% endblock%}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
<html>
    <head>
        <title>Rango</title>
    </head>
    {% block body_block %}
        <h1></h1>
        <div>
            <form id="category_form" method="post" action="/rango/django/add_page/">
                {% csrf_token%}
                {% for hidden in form.hidden_fields %}
                    {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{field.errors}}<br>
                    {{field.help_text}}<br>
                    {{field}}<br>
                {% endfor %}<br>
                <input type="submit" name="submit" value="Create Page" />
            </form>
        </div>
        {% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{%load static%}
<html>

<head>
    <title> Rango -
        {% block title_block %}
        How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></l\i>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
            <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
            <li><a href="{% url 'rango:login' %}">Login</a></li>
        </ul>
    </div>
</body>

</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

<html>

<head>
    <title>Rango</title>
</head>

{% block body_block %}
    <a href="/rango/">Index</a><br />
    <div>
        {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href='{{ page.url }}'> {{ page.title }} </a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}
        {% else %}
        The specified category does not exist.
        {% endif %}
    </div>
    <a href="./add_page/">Create a new Page</a>
</body>

</html>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static%}

{% block body_block %}
    <h1>Rango says {% if user.is_authenticated %} howdy {{user.username}} {% else %} hey there partner!{% endif %}</h1> <br />
        <strong>{{ boldmessage }}</strong>
    </div>
    <div>
        {% if categories %}
        <h2>Most Liked Categories</h2>
        <ul>
            {% for category in categories %}
            <li>
                <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
    </div>
    <div>
        {% if categories and pages %}
        <h2>Most Viewed Pages</h2>
        <ul>
            {% for page in pages %}
            <li>
                <a href="{{ page.url }}">{{ page.title }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}
    </div>
    <div>
        <a href="/rango/add_category/">Add a New Category</a><br />
        <a href="/rango/about/">About</a><br />
        <img src="/static/images/rango.jpg" alt="Picture of Rango" /><br>
    </div>
{% endblock %}

</html>

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static%}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label><br>
        <input type="username" id="password" name="username" value="" size="50"/><br>
        <label for="password">password:</label><br>
        <input type="password" id="password" name="password" value="" size="50"/><br>
        <input type="submit"  value="submit"/><br>
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Display each form -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}